#!/usr/bin/env bash

# trap ctrl-c and call ctrl_c()
trap ctrl_c INT
#trap ctrl-z and do nothing
trap "" SIGTSTP

function ctrl_c(){
    exec 2>.tmp     # redirect stderr output to .tmp

    pkill rosmaster # kill rosmaster explicitly

    sleep 1s        # give it time to output to terminal (avoids hang at the end)

    pkill rosout    # kill rosout explicitly
    pkill -P $$     # kill all processes started by this script (see below)
    rm -f .tmp      # delete stderr output
}


roscore &

sleep 1s #give roscore time to launch fully (including launching rosmaster and rosout under different processes)

rqt -s rqt_gcs &
ROS_NAMESPACE=/UAV1/stereo_cam rosrun stereo_image_proc stereo_image_proc &
ROS_NAMESPACE=/UAV1 rosrun machine_vision stereo_driver &
ROS_NAMESPACE=/UAV1 rosrun machine_vision object_detection &
if [ -z "$(lsusb | grep 'Leopard Imaging')" ]; then
  wait # stereo_camera not plugged in but the previous process has to be run in background or else the script exits prematurely, so we wait
else
  rosrun machine_vision disparity_view _topic:=/UAV1/stereo_cam/disparity
fi 
