#!/bin/bash

trap ctrl_cz SIGINT SIGTSTP

ctrl_cz()
{  
    lcar-kill $LOW $HIGH
    exit
}

lcar-kill()
{
    local low=$1
    local high=$2
    let last=high-1
    ylw='\033[1;33m' #Yellow
    nc='\033[0m' # No Color

    printf "\n\n${ylw}calling rosnode kill on UAV[$low-$last]${nc}\n\n"

    local id=$low

    while [ $id -lt $high ]; do
        for node in $( rosnode list | grep UAV$id ); do 
            rosnode kill $node
        done
        let id=id+1
    done
}

if [ -z "$1" ]; then 
    printf "    usage: lcar-fleet { kill <number> [<larger-number>] } | { <number> [<larger-number>] [mono] }\n\n"
    printf "       eg: lcar-fleet kill 10     | kills 10 lcar-bots with id's 0 - 9\n"
    printf "           lcar-fleet kill 10 20  | kills 10 lcar-bots with id's 10 - 19\n"
    printf "           lcar-fleet 10          | launches 10 lcar-bots with id's 0 - 9 with stereo_cams\n"
    printf "           lcar-fleet 10 20       | launches 10 lcar-bots with id's 10 - 19 with stereo_cams\n"
    printf "           lcar-fleet 10 mono     | launches 10 lcar-bots with id's 0 - 9 with mono_cams\n"
    printf "           lcar-fleet 10 20 mono  | launches 10 lcar-bots with id's 10 - 19 with mono_cams\n"
    exit
fi

if [ "$1" == "kill" ]; then
    if [ $3 ]; then
        lcar-kill $2 $3
    else 
        lcar-kill 0 $2
    fi
    exit
fi

LOW=0
HIGH=$1
MONO=""
if [ $2 ]; then
    if [ "$2" != "mono" ]; then
        LOW=$1
        HIGH=$2
    else
        MONO="$2"
    fi

    if [ $3 ]; then
        MONO="$3"
    fi
fi

ID=$LOW
while [ $ID -lt $HIGH ]; do
    lcar-bot $ID $MONO &
    let ID=ID+1
done

wait