#!/bin/bash

trap "ctrl_c" INT SIGINT SIGTSTP

ctrl_c()
{
    for node in $( rosnode list | grep V$ID ); do
        uavid=$( echo node | egrep -o [0-9]+ )
        if [ "$uavid" = "$ID" ]; then
            rosnode kill $node
        fi
    done

    exit
}

machine_name="$1"
if [ -z "$1" ]; then
    rosrun vehicle init_node # this node writes the vehicle_id given to it to a file
else
    rosrun vehicle init_node _machine_name:=$machine_name
fi

file_name="$HOME/vehicle_id"
if [ -f  $file_name ]; then
    ID=`cat $file_name` # parse the file to a variable
    rm -f $file_name
    echo "$file_name contains $ID"

    if [ "$ID" != "-1" ]; then
#       roslaunch gcs lcarbot_single_sim_vision.launch uav_id:="$ID"
		roslaunch gcs mavros_usb_cam.launch v_id:="$ID"
#      lcar-bot $ID
    fi
fi
